# Generated by Django 4.2.10 on 2024-02-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('fees', 'Fees'), ('exam', 'Exam'), ('medical', 'Medical'), ('drugs', 'Drugs'), ('others', 'Others')], default='fees', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unsolved', 'Unsolved'), ('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=20)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('evidence_picture', models.ImageField(blank=True, null=True, upload_to='issue_evidence/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
        ),
    ]
